### PR TITLE
UI breaks for storages on some resolutions #1887

### LINKED ISSUE #1887: UI breaks for storages on some resolutions
# Bug Description

The Storage page has some issues when displaying under some resolutions like `2560 x 1600`.

# Screenshots

Snip20201001_105

### PR DESCRIPTION
**Pull request by raw-letisso**
# Pull Request Description

This pull request closes strongbox/strongbox#1887.

# Acceptance Test

* [x] Building the code with `ng build` still works.
* [x] Building the code with `ng test` still works.
* [x] Building the code with `ng e2e` still works.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

# Code Review And Pre-Merge Checklist

* [x] My code follows the [coding convention](https://strongbox.github.io/developer-guide/coding-convention.html) of this project.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code in hard-to-understand areas.
* [x] My changes generate no new warnings.
* [x] I have added tests that prove my fix is effective or that my feature works.
* [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by raw-letisso** [comment]
Is something wrong with jenkins?

**Comment by carlspring** [comment]
Hi @raw-letisso ,

Thanks for your proposed fixes! @steve-todorov will have a look and get back to you.

**Comment by raw-letisso** [comment]
> Hi @raw-letisso ,
> 
> Thanks for your proposed fixes! @steve-todorov will have a look and get back to you.

thanks

**Comment by steve-todorov** [comment]
Sorry guys, I've been busy. Will check it out on Monday :)

**Comment by raw-letisso** [comment]
Hi guys, is everything alright with pull request?

**Review by steve-todorov — APPROVED** [review]

**Comment by steve-todorov** [comment]
Hey, thanks for the reminder and apologies for taking sooooo loooonnnggg! Congratulations on your first PR being merged! :)

**Pull request merged**
